# Generated by Django 3.0 on 2019-12-11 14:11

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
