# Generated by Django 3.0 on 2019-12-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191211_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('picture', models.ImageField(blank=True, upload_to='pictures/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='shopinfo',
            options={'ordering': ['-shop_name']},
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='about',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='bio',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='facebook',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='person_to_contact',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='specialty_item',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='twitter',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='year_established',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='images',
            field=models.ManyToManyField(blank=True, to='shop.Image'),
        ),
    ]
