# Generated by Django 3.0 on 2019-12-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191211_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
