# Generated by Django 3.0 on 2019-12-11 14:33

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shopinfo_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='contact_phone',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
    ]
