# Generated by Django 3.0 on 2019-12-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shopinfo_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
