# Generated by Django 3.0 on 2019-12-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20191211_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='address_2',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='zipcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
