# Generated by Django 3.0 on 2019-12-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shopinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='lat',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='lon',
            field=models.FloatField(default=1.0),
        ),
    ]
