# Generated by Django 3.0 on 2019-12-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_shopinfo_embed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='embed_id',
            field=models.CharField(default='', help_text='USE "+" SYMBOLS INSTEAD OF SPACE', max_length=200),
        ),
    ]
