# Generated by Django 3.0 on 2019-12-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20191214_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='embed_id',
            field=models.CharField(help_text='USE "+" SYMBOLS INSTEAD OF SPACE', max_length=200, null=True),
        ),
    ]
