# Generated by Django 3.0 on 2019-12-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20191214_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Featured'), (1, 'Featured')], default=0),
        ),
    ]
