# Generated by Django 3.0 on 2019-12-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20191223_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopinfo',
            old_name='status',
            new_name='featured',
        ),
    ]
