# Generated by Django 3.0 on 2020-01-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20191223_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopinfo',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='shopinfo',
            name='person_to_contact',
        ),
        migrations.RemoveField(
            model_name='shopinfo',
            name='specialty_item',
        ),
        migrations.RemoveField(
            model_name='shopinfo',
            name='images',
        ),
        migrations.AddField(
            model_name='shopinfo',
            name='images',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
