# Generated by Django 3.0 on 2020-01-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20200115_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
