# Generated by Django 3.0 on 2020-01-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_shopinfo_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='facebook',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='instagram',
            field=models.URLField(),
        ),
    ]
