# Generated by Django 3.0 on 2020-01-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200115_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='active',
            field=models.IntegerField(choices=[(0, 'NOT APPROVED'), (1, 'APPROVED')], default=0),
        ),
    ]
