# Generated by Django 3.0 on 2020-02-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_shopinfo_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopinfo',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='shopinfo',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='shopinfo',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='shopinfo',
            name='year_established',
        ),
    ]
