# Generated by Django 3.0 on 2020-01-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField(default='', max_length=1000)),
                ('slug', models.SlugField(max_length=120, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('pub_date', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
